[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
message_template = "{{commit_type}}: {{message}}"
example = "feat: this feature enables customize through config file"
schema = "<type>: <body>"
schema_pattern = "^[^{}]+$"
