---
repos:

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # The configuration of autopep8 is done via the .flake8
  # file in the root of the repo
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.1
    hooks:
      - id: markdownlint
        args: [--fix]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint

  - repo: https://github.com/Azure4DevOps/check-azure-bicep
    rev: v0.4.1
    hooks:
      - id: check-azure-bicep

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^configs/dev/powerbi/proddshbrd-report-config.json
      - id: check-json
        exclude: ^configs/dev/powerbi/proddshbrd-report-config.json
      - id: check-toml
      - id: check-xml
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ['--fix=auto']
        description: Forces to replace line ending by the UNIX 'lf' character
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: no-commit-to-branch
        args: [--branch, main]
