variables:
  - name: serviceConnection
    value: "INFRA_mo360proddashboards_DEV" # Replace this with your provisioned infrastructure service principal
    readonly: true

  - name: aadServiceConnection
    value: "INFRA_mo360proddashboards_AAD" # TODO: ADO service connection for AAD SP refresh
    readonly: true

  - name: dataprocServiceConnection # Add this with your newly provisoned data-processing service principal
    value: "DATAPROC_mo360proddashboards_DEV"
    readonly: true
