variables:
  - name: serviceConnection
    value: "ARM_mo360proddashboards_UAT" # TODO: ADO service connection for deployments
    readonly: true

  - name: aadServiceConnection
    value: "ARM_mo360proddashboards_AAD" # TODO: ADO service connection for AAD SP refresh
    readonly: true
